name: stale

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Run in debug mode without actually performing any operations on the repo.'
        required: false
        type: boolean
        default: true
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      -
        name: Run
        uses: actions/stale@v9
        with:
          ## Issue configuration
          days-before-issue-stale: 20
          days-before-issue-close: 10
          stale-issue-label: 'status/stale'
          close-issue-label: 'status/rotten'
          exempt-issue-labels: 'status/frozen'
          stale-issue-message: 'This issue is stale because it has been open 20 days with no activity. Remove stale label or comment or this will be closed in 10 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 30 days with no activity.'
          # Pull request configuration
          days-before-pr-stale: 20
          days-before-pr-close: 10
          stale-pr-message: 'This PR is stale because it has been open 20 days with no activity. Remove stale label or comment or this will be closed in 10 days.'
          close-pr-message: 'This PR was closed because it has been stalled for 30 days with no activity.'
          stale-pr-label: 'status/stale'
          close-pr-label: 'status/rotten'
          exempt-pr-labels: 'status/frozen'
          # General configuration
          exempt-milestones: true
          start-date: '2024-05-01T00:00:00+0000'
          debug-only: ${{ inputs.dry-run }}
